version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: translator
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  translation-service:
    build:
      context: ./services/translation-service
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPL_API_KEY=${DEEPL_API_KEY}
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./services/translation-service/src
          target: /app/src
        - action: sync
          path: ./services/translation-service/tsconfig.json
          target: /app/tsconfig.json
        - action: rebuild
          path: ./services/translation-service/package.json
    ports:
      - "3002:3002"
    depends_on:
      - redis

  websocket-service:
    build:
      context: ./services/websocket-service
      dockerfile: Dockerfile
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./services/websocket-service/src
          target: /app/src
        - action: sync
          path: ./services/websocket-service/tsconfig.json
          target: /app/tsconfig.json
        - action: rebuild
          path: ./services/websocket-service/package.json
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
      - TRANSLATION_SERVICE_URL=http://translation-service:3002
      - VARIABLE_SEPARATOR_URL=http://variable-separator:3003
      - DEEPL_SERVICE_URL=http://deepl-service:3004
    depends_on:
      - redis
      - translation-service
      - variable-separator
      - deepl-service

  variable-separator:
    build:
      context: ./services/variable-separator
      dockerfile: Dockerfile
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./services/variable-separator/src
          target: /app/src
        - action: sync
          path: ./services/variable-separator/tsconfig.json
          target: /app/tsconfig.json
        - action: rebuild
          path: ./services/variable-separator/package.json
    ports:
      - "3003:3003"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  deepl-service:
    build:
      context: ./services/deepl-service
      dockerfile: Dockerfile
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./services/deepl-service/src
          target: /app/src
        - action: sync
          path: ./services/deepl-service/tsconfig.json
          target: /app/tsconfig.json
        - action: rebuild
          path: ./services/deepl-service/package.json
    ports:
      - "3004:3004"
    environment:
      - DEEPL_API_KEY=${DEEPL_API_KEY}
    depends_on:
      - redis

volumes:
  redis-data:
  db-data:
