version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  translation-service:
    build:
      context: ./services/translation-service
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPL_API_KEY=${DEEPL_API_KEY}
    depends_on:
      - redis

  websocket-service:
    build:
      context: ./services/websocket-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - translation-service

volumes:
  redis-data:
