apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: hoi4-translate
spec:
  template:
    metadata:
      name: prisma-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: prisma-migrate
          image: <REGISTRY>/api-service:latest
          imagePullPolicy: IfNotPresent
          command: ["npx", "prisma", "migrate", "deploy"]
          envFrom:
            - secretRef:
                name: api-service-env
  backoffLimit: 1
