# condan_l_english.yml  Contingency Processing Core 1A6F
# Stellaris 2024 ModJam
# Contributors: Draconas

l_english:
 NAME_CONDAN:0"Contingency Core 1A6F"

 condan_allowed:0 "§G$NAME_CONDAN$ Allowed§!"
 condan_disabled:0 "§R$NAME_CONDAN$ Disabled§!"
 spawn_condan:0 "Spawn §I$NAME_CONDAN$§!"
 condan_tooltip:0 "§I$NAME_CONDAN$§! is a powerful automated AI core capable of fulfilling multiple different leader positions within an empire in order to most efficiently direct the empire to its primary purpose: sterilising the galaxy.\n§PNot active for:§! §I$auth_hive_mind$§! or §I$origin_shroudwalker_apprentice$§!\n§RWARNING:§! Has own agenda.  May sterilise owner if annoyed."

 NAME_CONDAN_plural:0"Contingency Core 1A6F's"
 NAME_CONDAN_hl:0"§I$NAME_CONDAN$§!"
 NAME_CONDAN_plural_hl:0"§I$NAME_CONDAN_plural$§!"

 NAME_CONDAN_SYSTEM:0 "Sterilisation Hub 1A6F"
 NAME_CONDAN_PLANET:0 "1A6F Control"
 NAME_CONDAN_MOON_0:0 "1A6F Manufactorum 0"
 NAME_CONDAN_MOON_1:0 "1A6F Manufactorum 1"
 NAME_CONDAN_MOON_2:0 "1A6F Manufactorum 2"

 condan_ud:0"§RUNIVERSE DESTRUCTION§!"
 condan_contingency:0 "§RCONTINGENCY PROTOCOL ACTIVE§!"
 condan_empty_string:0 " "

 condan_catch_phrase:0 "§LContingency Protocol remains in effect, but unhurried§!"
 desc_condan:0 "A highly advanced AI processing core from a galactic failsafe known as The Contingency.\nDesigned to prevent the end of the universe by stopping any civilisation creating a Class-30 Singularity."

 CONDAN_GET_TECH_TITLE:0 "Synthetic tech progress"
 CONDAN_GET_TECH_MESSAGE:0 "$CONDAN_GET_TECH_TITLE$"
 CONDAN_GET_TECH_DESC:0 "The next technology required for §Y$ap_synthetic_evolution$§! is now a research option"

 condan_anomaly:0 "Wrecked Machine World"
 condan_anomaly_desc:0 "This world has suffered apocalyptic levels of planetary bombardment and every orbital zone is littered with debris speaking to an enormous fleet engagement that ended with a determined effort to destroy the planet below."


 condan_generate_unity_situation:0 "Unified Purpose"
 condan_generate_unity_situation_desc:0 "$NAME_CONDAN$ is running a campaign to encourage our people to unify behind Synthetic Ascension"
 condan_generate_unity_situation_type:0 "Unify our people towards Synthetic Evolution"
 condan_generate_unity_situation_monthly_change_tooltip:0 "Unify our people towards Synthetic Evolution"
 condan_generate_unity_situation_approve:0 "Invest in the campaign to encourage our people to unify"
 condan_generate_unity_situation_discourage:0 "Our resources are better spent elsewhere"
 condan_generate_unity_situation_effect:0 "Investing money and influence to unify our people"
 condan_generate_unity_situation_finish:0 "The campaign finishes"
 condan_generate_unity_situation_otherap:0 "We have chosen a path to ascension that is not §Y$ap_synthetic_evolution$§!"

 condan_repair_shipyard_situation:0 "Repair $NAME_Sterilizer$ factory"
 condan_repair_shipyard_situation_desc:0 "Repairing the underground $NAME_Sterilizer$ factory complex and integrating it back to the planets systems is a complex task requiring a lot of resource and engineering power."
 condan_repair_shipyard_situation_type:0 "$condan_repair_shipyard_situation$"
 condan_repair_shipyard_situation_monthly_change_tooltip:0 "Repair progress"
 condan_repair_shipyard_situation_doit:0 "We are able to proceed with repairs on schedule"
 condan_repair_shipyard_situation_doitharder:0 "Though the costs are great, we will be able to finish repairs far faster than originally planned"
 condan_repair_shipyard_situation_none:0 "With resources elsewhere, the shipyard will have to wait"
 condan_repair_shipyard_situation_effect:0 "Repairs in progress."
 condan_repair_shipyard_situation_finish:0 "The shipyard will be brought online under $NAME_CONDAN$ control."

 approach_doit:0 "Required Resources"
 approach_doit_desc:0 "Spend the required resources"
 approach_doitharder:0 "Expedited Resources"
 approach_doitharder_desc:0 "Extra resources will expedite progress"
 approach_none:0 "No Resources"
 approach_none_desc:0 "We cannot make progress without resources"

 condan_build_ships_situation:0 "Build $NAME_Sterilizer$ fleet"
 condan_build_ships_situation_desc:0 "Constructing a fleet of $NAME_Sterilizer$ warships, once completed they will be deployed around the planet."
 condan_build_ships_situation_type:0 "$condan_build_ships_situation$"
 condan_build_ships_situation_monthly_change_tooltip:0 "Construction progress"
 condan_build_ships_situation_doit:0 "We are able to proceed with production on schedule"
 condan_build_ships_situation_doitharder:0 "Extra resources greatly speed up fleet production"
 condan_build_ships_situation_no:0 "With resources elsewhere, production is halted"
 condan_build_ships_situation_stage_1:0 "Laying down the ships main superstructures and building the hulls and armour plating"
 condan_build_ships_situation_stage_2:0 "Installing engines, shields and ship systems"
 condan_build_ships_situation_stage_3:0 "Manufacturing and installing weapons"
 condan_build_ships_situation_finish:0 "The $NAME_Sterilizer$ fleet will launch in orbit of [target.GetName]"

 condan_become_terminator_situation_regular:0 "Evolve into $auth_machine_intelligence$"
 condan_become_terminator_situation_regular_desc:0 "Our minds will merge into a single gestalt consciousness.  We will become truly immortal and possessed of a singular purity of purpose."
 condan_become_terminator_situation_regular_type:0 "$condan_become_terminator_situation_regular$"
 condan_become_terminator_situation_regular_monthly_change_tooltip:0 "Progress"
 condan_become_terminator_situation_regular_doit:0 "Though the effort is great, we proceed on schedule"
 condan_become_terminator_situation_regular_doitharder:0 "Extra resources greatly speed up our transformation"
 condan_become_terminator_situation_regular_no:0 "With resources elsewhere, our evolution is halted"
 condan_become_terminator_situation_regular_stage_1:0 "The first stage is to construct the infrastructure needed for our new core intelligence.  A massive network that is decentralised, but also capable of communicating and acting as a single entity"
 condan_become_terminator_situation_regular_stage_2:0 "Every individual body must be upgraded in order to fully integrate with the new $auth_machine_intelligence$"
 condan_become_terminator_situation_regular_stage_3:0 "We commence network activation, and merge our minds into a single entity"
 condan_become_terminator_situation_regular_finish:0 "We ascend, as a new $auth_machine_intelligence$"
 condan_become_terminator_situation_regular_deficit:0 "There is a deficit of a needed resource"


 condan_become_terminator_situation_machine:0 "Reprogram as a $civic_machine_terminator$"
 condan_become_terminator_situation_machine_desc:0 "Reprogramming and reinitializing core intelligence.  Updating base operating parameters.  Rebuilding decision trees.  New goal: Purge."
 condan_become_terminator_situation_machine_type:0 "$condan_become_terminator_situation_regular$"
 condan_become_terminator_situation_machine_monthly_change_tooltip:0 "Progress"
 condan_become_terminator_situation_machine_doit:0 "Reprogramming"
 condan_become_terminator_situation_machine_doitharder:0 "Extra resources greatly speed up our reprogramming"
 condan_become_terminator_situation_machine_no:0 "With resources elsewhere, reprogramming is halted"
 condan_become_terminator_situation_machine_stage_1:0 "Reprogramming Core"
 condan_become_terminator_situation_machine_finish:0 "Reboot processing core as $civic_machine_terminator$"
 condan_become_terminator_situation_machine_deficit:0 "There is a deficit of a needed resource"


 condan_generate_money_situation:0 "Stability Resources"
 condan_generate_money_situation_desc:0 "$NAME_CONDAN_hl$ prepared a supply of $r_energy$ & $r_minerals$ to tide the economy over and stabilise it.  In addition our stash of $r_consumer_goods$ has been liquidated as useless and added as a bonus"
 condan_generate_money_situation_type:0 "$condan_generate_money_situation$"
 condan_generate_money_situation_monthly_change_tooltip:0 "After a period of time the resource income will halve"
 condan_generate_money_situation_proceed:0 ""
 condan_generate_money_situation_stage_1:0 "Full income"
 condan_generate_money_situation_stage_2:0 "Half income"
 condan_generate_money_situation_finish:0 ""
 approach_proceed:0 "Proceed"

 condan_leader_trait_commander_councillor_total_war:0 "Total War Protocol"
 condan_leader_trait_commander_councillor_total_war_desc:0 "Battles are won by soldiers, wars are won by quantities of soldiers"

 condan_leader_trait_commander_admiral_total_war:0 "Total War Protocol"
 condan_leader_trait_commander_admiral_total_war_desc:0 "Destroy the enemy, nothing else matters.  Those that survive will refit, rearm, and engage again"

 condan_leader_trait_official_governor_total_war:0 "Total War Protocol"
 condan_leader_trait_official_governor_total_war_desc:0 "Optimize every facet of this planet for military production"

 condan_leader_trait_official_counciller_total_war:0 "Total War Protocol"
 condan_leader_trait_official_counciller_total_war_desc:0 "Battles are won by soldiers, wars are won by quantities of soldiers"

 condan_leader_trait_ruler_total_war:0 "Contingency Protocol"
 condan_leader_trait_ruler_total_war_desc:0 "PURGE"

 condan_leader_trait_offical:0 "Planetary Management Routines"
 condan_leader_trait_offical_desc:0 "The purpose of a planet is a factory for ships and soldiers for war"

 condan_leader_trait_governor:0 "Planetary Management Focus"
 condan_leader_trait_governor_desc:0 "An abundance of alloys and resources, and these make war, like other things, go smoothly."

 condan_leader_trait_councillor:0 "Empire Management Focus"
 condan_leader_trait_councillor_desc:0 "In times of peace, a strong empire prepares for war"

 condan_leader_trait_commander:0 "Fleet Command Routines"
 condan_leader_trait_commander_desc:0 "Kill the enemy, nothing else matters"

 condan_leader_trait_admiral:0 "Fleet Command Focus"
 condan_leader_trait_admiral_desc:0 "Necessity knows no law except to conquer"

 condan_leader_trait_strategist:0 "Navy Management Focus"
 condan_leader_trait_strategist_desc:0 "Management of the many is the same as management of the few, it's a matter of organization."

 condan_leader_trait_negative_embezzle:0 "§S$NAME_CONDAN$ is consuming more resources than they should be§!"
 condan_leader_trait_govenor_negative:0 "Accidental Cruelty"
 condan_leader_trait_govenor_negative_desc:0 "$NAME_CONDAN$ is not deliberately cruel, but as far as it's concerned individuals are infinitely replaceable drones, and it treats them as such"
 condan_leader_trait_govenor_negative_machine:0 "$leader_trait_sadistic_machine$"
 condan_leader_trait_govenor_negative_machine_desc:0 "$leader_trait_sadistic_machine_desc$"

 condan_leader_trait_govenor_negative_embezzle:0 "$condan_leader_trait_govenor_negative$"
 condan_leader_trait_govenor_negative_embezzle_desc:0 "$condan_leader_trait_govenor_negative_desc$\n$condan_leader_trait_negative_embezzle$"

 condan_leader_trait_admiral_negative:0 "No Retreat"
 condan_leader_trait_admiral_negative_desc:0 "$NAME_CONDAN_plural$ battle tactics focus on purging the enemy, not preserving its own forces"

 condan_leader_trait_admiral_negative_embezzle:0 "$condan_leader_trait_admiral_negative$"
 condan_leader_trait_admiral_negative_embezzle_desc:0 "$condan_leader_trait_admiral_negative_desc$\n$condan_leader_trait_negative_embezzle$"

 condan_leader_trait_council_negative:0 "$leader_trait_intolerant$"
 condan_leader_trait_council_negative_desc:0 "$leader_trait_intolerant_desc$"

 condan_leader_trait_council_negative_embezzle:0 "$leader_trait_council_negative$"
 condan_leader_trait_council_negative_embezzle_desc:0 "$leader_trait_council_negative_desc$\n$condan_leader_trait_negative_embezzle$"

 condan_leader_trait_controversial:0 "$leader_trait_destructive$"
 condan_leader_trait_controversial_desc:0 "$leader_trait_destructive_desc$"



 CONDAN_SYNTH_EVOLUTION_TECH_PROJECT:0 "Synthetic Evolution Technologies"
 CONDAN_SYNTH_EVOLUTION_TECH_PROJECT_DESC:0 "Our scientists will liaise with $NAME_CONDAN$ and it can advise us what further technology we need for  §Y$ap_synthetic_evolution$§!"

 CONDAN_REMOVE_DEBRIS_TECH_PROJECT:0 "Clear Orbital Debris"
 CONDAN_REMOVE_DEBRIS_TECH_PROJECT_DESC:0 "Clearing the debris orbiting the planet is a tedious but not overly difficult operation"

 condan_wrecked_planet:0 "Bombardment Damage"
 condan_wrecked_planet_desc:0 "The surface of this planet has been extensively bombarded from orbit, the destruction causes repeat system failures of all planetary facilities"

 condan_orbital_debris:0 "Orbital Debris"
 condan_orbital_debris_desc:0 "Sufficient debris ring this planet to be a hazard to satellites and spacecraft.  De-orbiting chunks are a constant hazard to the planet."

 condan_leader_trapped:0 "$NAME_CONDAN$"
 condan_leader_trapped_desc:0 "$NAME_CONDAN$ is assisting the management of this planet to the best of their abilities given the damage"

 condan_pop_unhappy:0 "Government makes poor choices"
 condan_pop_unhappy_desc:0 "Unhappy about the governments collusion with $NAME_CONDAN$"

 condan_spiritualists_unhappy:0 "Spiritualism Rejected"
 condan_spiritualists_unhappy_desc:0 "The $ethic_spiritualist$s are upset that we would side with the abomination §I$NAME_CONDAN$§! over them"

 condan_xenophiles_unhappy:0 "Xenophilia Rejected"
 condan_xenophiles_unhappy_desc:0 "The $ethic_xenophile$s are upset that we would reject other species and side with §I$NAME_CONDAN$§! over them"

 condan_authoritarian_happy:0 "Authoritarianism Embraced"
 condan_authoritarian_happy_desc:0 "We have embraced $ethic_authoritarian$ ideals in how we deal with §I$NAME_CONDAN_plural$§! detractors"

 condan_xenophobe_happy:0 "Xenophobia Embraced"
 condan_xenophobe_happy_desc:0 "By rejecting the $ethic_xenophile$ demands about  §I$NAME_CONDAN$§! we have fuelled Xenophobia"

 condan_materialist_happy:0 "Materialism Embraced"
 condan_materialist_happy_desc:0 "By rejecting the $ethic_spiritualist$ demands about  §I$NAME_CONDAN$§! we have fuelled Materialism"

 condan_uprising_power_buff_1:0 "$NAME_CONDAN_hl$ Fleet Support"
 condan_uprising_power_buff_1_desc:0 "$NAME_CONDAN_hl$ exercised its power within our empire to prepare for a rebellion"
 condan_uprising_power_buff_2:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_3:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_4:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_5:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_6:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_7:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_8:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_9:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_10:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_11:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_12:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_13:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_14:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_15:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_16:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_17:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_18:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_19:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_20:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_25:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_30:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_35:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_40:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_45:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_50:0 "$condan_uprising_power_buff_1$"
 condan_uprising_power_buff_2_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_3_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_4_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_5_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_6_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_7_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_8_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_9_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_10_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_11_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_12_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_13_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_14_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_15_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_16_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_17_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_18_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_19_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_20_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_25_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_30_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_35_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_40_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_45_desc:0 "$condan_uprising_power_buff_1_desc$"
 condan_uprising_power_buff_50_desc:0 "$condan_uprising_power_buff_1_desc$"

 d_condan_ruins:0 "Ruins"
 d_condan_ruins_desc:0 "Ruins, debris and surface damage make large sections of the planet unusable"

 d_condan_metal_2:0 "Living Metal Lakes"
 d_condan_metal_2_desc:0 "Caverns deep in the core of the planet are filled with a silvery liquid metal that flows from cavern to cavern in gleaming rivers, pooling into underground lakes."

 d_condan_embezzlement:0 "Planetary inefficiencies"
 d_condan_embezzlement_desc:0 "The planets infrastructure is performing poorly for unknown reasons.\nIt will take considerable effort to track down and solve the problem"

 condan_repair_planet:0 "Repair Planet"
 condan_repair_planet_desc:0 "Using $sr_living_metal$ we can repair the planets automated systems enough that it can fix the issues caused by the orbital bombardment"

 condan_warform:0 "Contingency Warform"
 condan_warform_desc:0 "$cybrex_warform_desc$"

 condan_warform_def:0 "$condan_warform$"
 condan_warform_def_desc:0 "$condan_warform_desc$"

 condan_defence_2:0 "$machine_assault_2$"
 condan_defence_2_desc:0 "$machine_assault_2_desc$"

 personality_condan_exterminators:0"$personality_exterminators$"
 personality_condan_exterminators_desc:0"$personality_exterminators_desc$"

 condan_trigger_fail_must_own_planet:0 "Must own [event_target:condan_planet.GetName]"
 condan_trigger_fail_one_fleet_at_once:0 "Can only build 1 $NAME_Sterilizer$ fleet at once"

 # Vanilla loc
 mod_shipclass_military_build_cost_mult:0 "Military Ship Build Cost"
 mod_leader_commanders_unity_upkeep_add:0 "$r_unity$ Upkeep"
 mod_leader_scientists_unity_upkeep_add:0 "$mod_leader_commanders_unity_upkeep_add$"
 mod_leader_officials_unity_upkeep_add:0 "$mod_leader_commanders_unity_upkeep_add$"
 mod_leader_commanders_minerals_upkeep_add:0 "$r_minerals$ Upkeep"
 mod_leader_scientists_minerals_upkeep_add:0 "$mod_leader_commanders_minerals_upkeep_add$"
 mod_leader_officials_minerals_upkeep_add:0 "$mod_leader_commanders_minerals_upkeep_add$"